public extension Country {
    var languages: (main: Language, additional: [Language]) {
        switch self {
        case .AE, .IQ, .JO, .KW, .LY, .OM, .QA, .SA, .YE: return (main: .en_GB, additional: [.ar_SA])
        case .AF, .AG, .AI, .AL, .AM, .AO, .AZ, .BB, .BG, .BH, .BM, .BN, .BS, .BT, .BW, .BY, .CV, .DM, .EE, .FJ, .FM, .GB, .GD, .GE, .GH, .GM, .GY, .IE, .IS, .JM, .KE, .KG, .KN, .KY, .KZ, .LC, .LK, .LR, .LT, .LV, .MD, .MK, .MM, .MN, .MS, .MT, .MV, .MW, .MY, .MZ, .NA, .NE, .NG, .NP, .NR, .NZ, .PG, .PH, .PK, .PW, .SB, .SI, .SL, .ST, .SZ, .TC, .TJ, .TM, .TO, .TZ, .UG, .UZ, .VC, .VG, .XK, .ZA, .ZM, .ZW: return (main: .en_GB, additional: [])
        case .AR, .CL, .CO, .CR, .EC, .GT, .HN, .NI, .PA, .PE, .PY, .SV, .VE: return (main: .es_MX, additional: [.en_GB])
        case .AT, .DE: return (main: .de_DE, additional: [.en_GB])
        case .AU: return (main: .en_AU, additional: [])
        case .BA, .HR, .ME, .RS: return (main: .en_GB, additional: [.hr])
        case .BE: return (main: .en_GB, additional: [.fr_FR, .nl_NL])
        case .BF, .BJ, .CD, .CG, .GW, .KH, .LA, .MG, .ML, .MU, .RW, .SC, .SN, .TD, .TT, .VU: return (main: .en_GB, additional: [.fr_FR])
        case .BO: return (main: .es_ES, additional: [.en_GB])
        case .BR: return (main: .pt_BR, additional: [.en_GB])
        case .BZ: return (main: .en_GB, additional: [.es_ES])
        case .CA: return (main: .en_CA, additional: [.fr_CA])
        case .CH: return (main: .de_DE, additional: [.en_GB, .fr_FR, .it])
        case .CI, .CM, .FR, .GA: return (main: .fr_FR, additional: [.en_GB])
        case .CN: return (main: .zh_Hans, additional: [.en_GB])
        case .CY, .TR: return (main: .en_GB, additional: [.tr])
        case .CZ: return (main: .en_GB, additional: [.cs])
        case .DK: return (main: .en_GB, additional: [.da])
        case .DO: return (main: .es_MX, additional: [.fr_FR])
        case .DZ, .EG, .LB, .MA, .MR, .TN: return (main: .en_GB, additional: [.ar_SA, .fr_FR])
        case .ES: return (main: .es_ES, additional: [.ca, .en_GB])
        case .FI: return (main: .en_GB, additional: [.fi])
        case .GR: return (main: .el, additional: [])
        case .HK, .MO, .TW: return (main: .zh_Hant, additional: [.en_GB])
        case .HU: return (main: .en_GB, additional: [.hu])
        case .ID: return (main: .en_GB, additional: [.id])
        case .IL: return (main: .en_GB, additional: [.he])
        case .IN: return (main: .en_GB, additional: [.hi])
        case .IT: return (main: .it, additional: [.en_GB])
        case .JP: return (main: .ja, additional: [.en_GB])
        case .KR: return (main: .ko, additional: [.en_GB])
        case .LU: return (main: .en_GB, additional: [.de_DE, .fr_FR])
        case .MX: return (main: .es_MX, additional: [])
        case .NL: return (main: .nl_NL, additional: [.en_GB])
        case .NO: return (main: .en_GB, additional: [.no])
        case .PL: return (main: .en_GB, additional: [.pl])
        case .PT: return (main: .pt_PT, additional: [.en_GB])
        case .RO: return (main: .en_GB, additional: [.ro])
        case .RU: return (main: .ru, additional: [.en_GB, .uk])
        case .SE: return (main: .sv, additional: [.en_GB])
        case .SG: return (main: .en_GB, additional: [.zh_Hans])
        case .SK: return (main: .en_GB, additional: [.sk])
        case .SR: return (main: .en_GB, additional: [.nl_NL])
        case .TH: return (main: .en_GB, additional: [.th])
        case .UA: return (main: .en_GB, additional: [.ru, .uk])
        case .US: return (main: .en_US, additional: [.ar_SA, .es_MX, .fr_FR, .ko, .pt_BR, .ru, .vi, .zh_Hans, .zh_Hant])
        case .UY: return (main: .en_GB, additional: [.es_MX])
        case .VN: return (main: .en_GB, additional: [.vi])
        }
    }
}
